theme: "hugo-PaperMod"
baseURL: alexpaynter.netlify.app 
languageCode: en-us
title: Alex Paynter

params:
    defaultTheme: auto
    profileMode:
        enabled: true
        title: links ğŸ‘‡      menu â˜ 
        subtitle: "(site under construction ğŸªšğŸ”¨ğŸ”¬ğŸ¨)"
        buttons:
            - name: Blog
              url: posts
            - name: Tags
              url: tags
    socialIcons:
        - name: github
          url: "https://github.com/alexpaynter"
        - name: email
          url: about/
        - name: RsS
          url: "index.xml"

menu:
    main:
        - name: Main
          url:  
          weight: 2 
        - name: Blog
          url: post/
          weight: 3 
        - name: Projects
          url: project/
          weight: 3.5
        - name: Links
          url: link/
          weight: 4 
        - name: About
          url: about/
          weight: 5
