theme: "hugo-PaperMod"
baseURL: http://example.org/
languageCode: en-us
title: Sitey McSiteFace

params:
    profileMode:
        enabled: true
        title: PaperMod
        subtitle: "â˜„ï¸ Fast | â˜ï¸ Fluent | ğŸŒ™ Smooth | ğŸ“± Responsive"
        buttons:
            - name: Blog
              url: posts
            - name: Tags
              url: tags

menu:
    main:
        - name: Main
          url:  
          weight: 2 
        - name: Blog
          url: post/
          weight: 3 
        - name: Links
          url: link/
          weight: 4 
        - name: About
          url:  
          weight: 5
