theme: "hugo-PaperMod"
baseURL: https://alexpaynter.netlify.app 
languageCode: en-us
title: Alex Paynter

params:
    defaultTheme: auto
    profileMode:
        enabled: true
        title: links ğŸ‘‡      menu â˜ 
        subtitle: "(site under construction ğŸªšğŸ”¨ğŸ”¬ğŸ¨)"
    socialIcons:
        - name: github
          url: "https://github.com/alexpaynter"
        - name: email
          url: about/
        - name: RSS
          url: "index.xml"
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
          

menu:
    main:
        - name: Main
          url:  
          weight: 2 
        - name: Blog
          url: post/
          weight: 3 
        - name: Projects
          url: project/
          weight: 3.5
        - name: Links
          url: link/
          weight: 4 
        - name: Search
          url: search/
        - name: About
          url: about/
          weight: 5
          
outputs:
    home:
        - HTML
        - RSS 
        - JSON
